### ISSUE TITLE
[BUG] Does `##` has special meaning in Twig?

### ISSUE THREAD

**Issue by jfcherng** [Sublime-Instincts/BetterTwig#1]
### Summary

Does `##` has special meaning in Twig?

https://github.com/Sublime-Instincts/BetterTwig/blob/0811fb5c2bc2900c3b228efd9ff6e1b9112ee54f/resources/metadata/Comments.tmPreferences#L13-L18

### Expected/Actual Behaviour

It's scoped and used as comments in this repo. But I don't think it is since Twig 3.0.5 still outputs it as is. Or it's legacy syntax? The only way to write comments in Twig is `{# ... #}` afaik.

### Environment

[The environment you experienced this bug in.]

- Sublime Text build: 4181
- BetterTwig version: v1.0.0

**Comment by Ultra-Instinct-05** [comment]
Thanks for the report. Jinja2 has the notion of line comments (& uses `##` for in line comments) & `{# #}` for block comments. And I naturally carried this over to Twig going by how similar the two templating languages are. After searching online for some time, It looks like Twig doesn't have the notion of inline comments. I'll have this fixed in the next version.

**Comment by Ultra-Instinct-05** [comment]
This should be fixed in v1.0.1

**Comment by jfcherng** [comment]
Closed since confirmed fixed.
